import { config } from 'dotenv';
config({ path: `.env` });

// const CREDENTIALS = process.env.CREDENTIALS === 'true'
export const {
  NODE_ENV, PORT, DB_URI,
  DB_HOST, DB_PORT, DB_NAME,
  DB_TYPE, HOST, DB_USER, DB_PASSWORD
  , LOG_FORMAT, LOG_DIR, GPT_KEY, SENDGRID_API_KEY,
  JWT_SECRET_KEY, JWT_EXPIRATION_HOURS, SENDER_NUMBER,
  TWILIO_SID, TWILIO_TOKEN, CONTENT_SID,
  JWT_ISSUER, JWT_REFRESH_TOKEN_EXPIRES,
  SENDER_EMAIL, JWT_ACCESS_TOKEN_EXPIRES,
  SMTP_HOSTNAME, SMTP_USERNAME, SMTP_PASSWORD, SMTP_PORT, SMTP_SECURE,
  APP_NAME, APP_URL, APP_LOGO, APP_EMAIL, BANK_NAME, BANK_CODE, COIN_MARKET_API_KEY
} = { ...process.env, APP_LOGO: '' } as any;

